[book]
authors = ["JoseSK999"]
language = "en"
multilingual = false
src = "src"
title = "Floresta Docs"

[output.html]
git-repository-url = "https://github.com/JoseSK999/floresta-docs"

[output.html.playground]
runnable = false

[output.html.fold]
enable = true
level = 1

[output.linkcheck]
follow-web-links = true
# ignore only the bitcoin/bips mediawiki pages
exclude = [ 'github\.com/bitcoin/bips/blob/master/bip-.*\.mediawiki', 'https://blog.dlsouza.lol/2023/09/28/pow-fraud-proof.html' ]

[preprocessor.quiz]
