[book]
authors = ["JoseSK999"]
language = "en"
multilingual = false
src = "src"
title = "Floresta Docs"

[output.html]
git-repository-url = "https://github.com/JoseSK999/floresta-docs"

[output.html.playground]
runnable = false

[output.html.fold]
enable = true
level = 1

[output.linkcheck]
follow-web-links = true

[output.linkcheck.http-headers]
# some sites return 404 on HEAD unless we explicitly ask for HTML
'crates\.io' = ["Accept: text/html"]
'github\.com/bitcoin/bips/blob/master/bip-.*\.mediawiki' = ["Accept: text/html"]

[preprocessor.quiz]
