[book]
authors = ["JoseSK999"]
language = "en"
multilingual = false
src = "src"
title = "Floresta Docs"

[output.html.playground]
runnable = false

[output.html.fold]
enable = true
level = 1

[output.linkcheck]
follow-web-links = true

[preprocessor.quiz]
